### ISSUE TITLE
“wrong password” error msg when containes # and %

### ISSUE THREAD

**Issue by Joe-H-Yu** [exsat-network/exsat-client#55]
Customer feedback:
I am not sure what happened, but wanted to relay this information along. 

This morning we had a data center outage, which caused our validator to restart automatically (as it should).

When it restarted, it restarted successfully, but it threw an error showing:

Key derivation failed - possibly wrong password

The password and configuration files had not changed, but suddenly our password was not working. I checked everything and the password was correct, but I could not restart it.

I had to delete our keystore and reimport the account from the seed phrase. I used the same password, and again received the same error message about the “wrong password”.

So I deleted it again, and used a different password - and this time it worked. The password I used this time was more simple, and only included numbers/letters. 

The password that didn’t work contained # and % - so potentially there’s a problem with special characters being used as the validator password? Maybe the configuration file reader is interpreting them wrong? I’m not entirely sure.

thanks for feedback,  Micheal from the EOS USA also met the problem,  because the password is saved in the  .env file,  it will interpret the string as comment if it contains #.

I think @defiob will help to find out a solution in the next version,  or if you have a good idea,  welcome to make a pr.😊

Wrapping the string in quotes ”some#thing” in the .env file might work as the commander saves it? 

I didn’t try, I was too busy just trying to bring the service online 😅

**Comment by RobinHolmes** [comment]
has done
https://github.com/exsat-network/exsat-client/pull/56
